version: "3"

services:
  mysql:
    container_name: db
    build:
      context: ./
      dockerfile: ./mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: echo-rest
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  echo-app:
    container_name: echo-app
    build:
      context: echo-app/
      dockerfile: Dockerfile
    volumes:
      - ./echo-app/:/go/src/github.com/soutaschool/echo-rest/echo-app
    ports:
      - "8080:8080"
    depends_on:
      - db
